<?php

namespace AppBundle\Repository\Referentiel;

use Doctrine\ORM\EntityRepository;

/**
 * ControleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleRepository extends EntityRepository
{
    public function getControleStd()
    {
        $qB = $this->createQueryBuilder('c')
                ->orderBy('c.libelle');
        
        $qry = $qB->getQuery();
        
        return $qry->getResult();
    }
}
