<?php

namespace AppBundle\Repository\Referentiel;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    
    public function getAll()
    {
        $qB = $this->createQueryBuilder('d')
                ->select('d.documentType');
        
        $qry = $qB->getQuery();
        
        $libellesDocument = array();
        foreach ($qry->getScalarResult() as $document) {
            $libellesDocument[] = $document['documentType'];
        }
        
        return $libellesDocument;
    }
    
    public function getDocumentsStd()
    {
        $qB = $this->createQueryBuilder('d')
                ->orderBy('d.documentType');
        
        $qry = $qB->getQuery();
        
        return $qry->getResult();
    }
    
}
