<?php

namespace AppBundle\Repository\Referentiel;

use Doctrine\ORM\EntityRepository;

/**
 * InterlocuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterlocuteurRepository extends EntityRepository
{
    
    public function getInterlocuteurs()
    {
        $qB = $this->createQueryBuilder('i');
        $qB->leftJoin('i.documents', 'd')
                ->addSelect('d')
                ->orderBy('i.libelle', 'ASC');
        
        $qry = $qB->getQuery();
        
        return $qry->getResult();
    }
    
    public function getInterlocuteursStd()
    {
        $qB = $this->createQueryBuilder('i')
                ->orderBy('i.libelle');
        
        $qry = $qB->getQuery();
        
        return $qry->getResult();
    }
    
}
