<?php

namespace AppBundle\Repository\Referentiel;

use Doctrine\ORM\EntityRepository;

/**
 * TransmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmissionRepository extends EntityRepository {

    public function getAll() {
        $qB = $this->createQueryBuilder('t')
                ->select(array('t.id', 't.libelle'))
                ->orderBy('t.libelle', 'ASC');
        $qry = $qB->getQuery()->getResult();
        return $qry;
    }

    public function getTransmissions() {
        $qB = $this->createQueryBuilder('t')
                ->select('t.libelle');
//        $qB->expr()->isNull('s.dateSuppression');

        $qry = $qB->getQuery();

        $libellesStatut = array();
        foreach ($qry->getScalarResult() as $statut) {
            $libellesStatut[] = $statut['libelle'];
        }

        return $libellesStatut;
    }

}
