<?php

namespace Proxies\__CG__\AppBundle\Entity\Referentiel;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cabinet extends \AppBundle\Entity\Referentiel\Cabinet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numero', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'rue', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'ville', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numeroStdPhone', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numeroLgRouge', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numeroFax', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'permanencePhone', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'permanenceExpert', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'equipeExpert', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'equipeAssistante', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'operations');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numero', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'rue', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'codePostal', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'ville', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numeroStdPhone', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numeroLgRouge', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'numeroFax', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'permanencePhone', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'permanenceExpert', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'equipeExpert', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'equipeAssistante', '' . "\0" . 'AppBundle\\Entity\\Referentiel\\Cabinet' . "\0" . 'operations');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cabinet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setRue($rue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRue', array($rue));

        return parent::setRue($rue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRue', array());

        return parent::getRue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroStdPhone($numeroStdPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroStdPhone', array($numeroStdPhone));

        return parent::setNumeroStdPhone($numeroStdPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroStdPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroStdPhone', array());

        return parent::getNumeroStdPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroLgRouge($numeroLgRouge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroLgRouge', array($numeroLgRouge));

        return parent::setNumeroLgRouge($numeroLgRouge);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroLgRouge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroLgRouge', array());

        return parent::getNumeroLgRouge();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroFax($numeroFax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroFax', array($numeroFax));

        return parent::setNumeroFax($numeroFax);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroFax', array());

        return parent::getNumeroFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermanencePhone($permanencePhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermanencePhone', array($permanencePhone));

        return parent::setPermanencePhone($permanencePhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermanencePhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermanencePhone', array());

        return parent::getPermanencePhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermanenceExpert($permanenceExpert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermanenceExpert', array($permanenceExpert));

        return parent::setPermanenceExpert($permanenceExpert);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermanenceExpert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermanenceExpert', array());

        return parent::getPermanenceExpert();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipeExpert($equipeExpert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipeExpert', array($equipeExpert));

        return parent::setEquipeExpert($equipeExpert);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipeExpert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipeExpert', array());

        return parent::getEquipeExpert();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipeAssistante($equipeAssistante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipeAssistante', array($equipeAssistante));

        return parent::setEquipeAssistante($equipeAssistante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipeAssistante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipeAssistante', array());

        return parent::getEquipeAssistante();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperation(\AppBundle\Entity\Operation $operations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperation', array($operations));

        return parent::addOperation($operations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperation(\AppBundle\Entity\Operation $operations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperation', array($operations));

        return parent::removeOperation($operations);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperations', array());

        return parent::getOperations();
    }

    /**
     * {@inheritDoc}
     */
    public function getDatas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatas', array());

        return parent::getDatas();
    }

}
